### ISSUE TITLE
FastMSA 프레임워크에서 실행되도록 코드 완성하기

### ISSUE THREAD

**Issue by cloudeyes** [2021-msa-study/smartcloset#10]
Domain-Model 브랜치에 올린 스켈레톤 코드를 수정해서 동작 가능한 코드를 완성해주세요.

**해야할 작업**
- Aggregate 클래스 만들기
- ORM 매핑하기
- UoW 로 서비스 테스트하기

FastMSA 프레임웍의 사용 예제는 fastmsa 레포지터리의 `01-kickoff-setup` 브랜치에서 `tests` 디렉토리를 보면 확인하실 수 있습니다.

**Comment by cloudeyes** [comment]
@lyonmoon @sjw451 아래 문서를 참고하시면 Aggregate 이해하는데 도움이 많이 되실거에요.

- https://cloudeyes.github.io/2021-msa-study/guide/07.html

**Comment by lyonmoon** [comment]
Aggregate 정리해주신내용이 도움이 많이됩니다!
예제에서는 SKU를 기분으로 Product를 만들었는데, 이걸 smart closet 도메인에 적용할 때 partition 자체가 aggregate가 되면 될거같은데, 예제랑은 조금 상황이 달라서 maker 기준으로 aggregate클래스를 만드는게 맞을지도 생각해보았습니다.
아직 코드 반영은 못하였는데, API와 정리문서 참고해서 내일 이어서 반영해보겠습니다.
